/*
 * Hotel Management System for Pavana Hotel Kochchikade
 * Information Technology Project - 2016
 * Project ID   : ITP_WD_16_B1_06
 * Supervisor   : Mrs. Asanthika Imbulpitiya
 *
 * Student Name : Kaushalya R.U
 * IT Number    : IT14087202
 */
package app.employee_management;

import static java.lang.Integer.parseInt;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import model.employee_management.Leave_Requirements_Model;
import source.ImageProcessing;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import source.Validation;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Dhanuka Perera
 */
public class Leave_Requirements_Frame extends javax.swing.JPanel {

    ImageProcessing changebtnImage = new ImageProcessing();
     Validation val = new Validation ();
    public Leave_Requirements_Model Leave = new Leave_Requirements_Model();
    public static String cancel="Not Cancel";
    
    boolean flag = false;
    public Leave_Requirements_Frame() {
        initComponents();
        Leave.loadTable("leave_requirement",tblLeaveRequirements);
        txtCurrentDate.setText(test());
        Leave.LoadEmployeeID();
    }
    
    private String test()
    {
        String currentDateTime;
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
       java.util.Date dateobj = new java.util.Date();
       return currentDateTime= df.format(dateobj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlToolBox = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        lblDisplayBy = new javax.swing.JLabel();
        cmbDisplayBy = new javax.swing.JComboBox<>();
        lblOrderBy = new javax.swing.JLabel();
        cmbOrderBy = new javax.swing.JComboBox<>();
        lblSearchBy = new javax.swing.JLabel();
        cmbSearchBy = new javax.swing.JComboBox<>();
        lblSearchIcon = new javax.swing.JLabel();
        txtSearchBox = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        pnlLeaveRequirements = new javax.swing.JPanel();
        pnlSideA = new javax.swing.JPanel();
        lblEmployeeID = new javax.swing.JLabel();
        valCkEmployeeID = new javax.swing.JLabel();
        valCkLeaveDate = new javax.swing.JLabel();
        lblLeaveDate = new javax.swing.JLabel();
        lblNoOfAbsences = new javax.swing.JLabel();
        valCkNoOfAbsences = new javax.swing.JLabel();
        txtNoOfAbsences = new javax.swing.JTextField();
        valCkApproval = new javax.swing.JLabel();
        dtpLeaveDate = new com.toedter.calendar.JDateChooser();
        cmbEmployeeID = new javax.swing.JComboBox<>();
        lblLeaveRecordNo = new javax.swing.JLabel();
        txtLeaveRequirementNo = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        pnlSideB = new javax.swing.JPanel();
        lblRequiredLeaves = new javax.swing.JLabel();
        valCkTo = new javax.swing.JLabel();
        lblCurrentDate = new javax.swing.JLabel();
        lblLeavesForaMonth = new javax.swing.JLabel();
        txtLeavesForaMonthD = new javax.swing.JTextField();
        valCkLeavesForaMonth = new javax.swing.JLabel();
        valCkCurrentDate = new javax.swing.JLabel();
        txtRequiredLeaves = new javax.swing.JTextField();
        txtCurrentDate = new javax.swing.JTextField();
        txtApproval = new javax.swing.JTextField();
        lblApproval = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeaveRequirements = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlToolBox.setBackground(new java.awt.Color(221, 221, 221));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Add_def.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Update_def.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Delete_def.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Clear_def.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Report_def.png"))); // NOI18N
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlToolBoxLayout = new javax.swing.GroupLayout(pnlToolBox);
        pnlToolBox.setLayout(pnlToolBoxLayout);
        pnlToolBoxLayout.setHorizontalGroup(
            pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolBoxLayout.createSequentialGroup()
                .addComponent(btnAdd)
                .addGap(0, 0, 0)
                .addComponent(btnUpdate)
                .addGap(0, 0, 0)
                .addComponent(btnDelete)
                .addGap(0, 0, 0)
                .addComponent(btnClear)
                .addGap(0, 0, 0)
                .addComponent(btnReport)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlToolBoxLayout.setVerticalGroup(
            pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolBoxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        lblDisplayBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDisplayBy.setText("Display By :");

        cmbDisplayBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbDisplayBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblOrderBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrderBy.setText("Order By :");

        cmbOrderBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbOrderBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSearchBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchBy.setText("Search By :");

        cmbSearchBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leave Requirement No", "Employee ID", "Leave Date", "Required Leaves", "Current Date", "Absences", "Leaves For a Month", "Approval" }));

        lblSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/searchIcon.png"))); // NOI18N

        txtSearchBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchBox.setText("Search...");
        txtSearchBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchBoxMouseClicked(evt);
            }
        });
        txtSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBoxKeyReleased(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/searchButton.png"))); // NOI18N

        pnlLeaveRequirements.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeaveRequirements.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlSideA.setBackground(new java.awt.Color(255, 255, 255));

        lblEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmployeeID.setText("Employee ID");

        valCkEmployeeID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        valCkLeaveDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblLeaveDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLeaveDate.setText("Leave Date");

        lblNoOfAbsences.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNoOfAbsences.setText("No Of Absences");

        valCkNoOfAbsences.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        txtNoOfAbsences.setEditable(false);
        txtNoOfAbsences.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNoOfAbsences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfAbsencesActionPerformed(evt);
            }
        });
        txtNoOfAbsences.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoOfAbsencesKeyReleased(evt);
            }
        });

        valCkApproval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        cmbEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbEmployeeID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEmployeeID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbEmployeeIDMouseClicked(evt);
            }
        });
        cmbEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmployeeIDActionPerformed(evt);
            }
        });
        cmbEmployeeID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbEmployeeIDPropertyChange(evt);
            }
        });
        cmbEmployeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbEmployeeIDKeyReleased(evt);
            }
        });

        lblLeaveRecordNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLeaveRecordNo.setText("Leave Record No");

        txtLeaveRequirementNo.setEditable(false);

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCheck.setText("Check");
        btnCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSideALayout = new javax.swing.GroupLayout(pnlSideA);
        pnlSideA.setLayout(pnlSideALayout);
        pnlSideALayout.setHorizontalGroup(
            pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSideALayout.createSequentialGroup()
                                .addComponent(lblLeaveDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtpLeaveDate, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                            .addGroup(pnlSideALayout.createSequentialGroup()
                                .addComponent(lblNoOfAbsences, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNoOfAbsences, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valCkNoOfAbsences)
                            .addComponent(valCkApproval)))
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblLeaveRecordNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEmployeeID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLeaveRequirementNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valCkEmployeeID)
                            .addComponent(valCkLeaveDate))))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(148, 148, 148))
        );
        pnlSideALayout.setVerticalGroup(
            pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmployeeID)
                        .addComponent(cmbEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valCkEmployeeID))
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valCkLeaveDate)
                            .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLeaveRecordNo)
                                .addComponent(txtLeaveRequirementNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLeaveDate))
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valCkNoOfAbsences)
                            .addComponent(dtpLeaveDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valCkApproval)
                            .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNoOfAbsences)
                                .addComponent(txtNoOfAbsences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnCheck))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pnlSideB.setBackground(new java.awt.Color(255, 255, 255));

        lblRequiredLeaves.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRequiredLeaves.setText("Required Leaves");

        valCkTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblCurrentDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurrentDate.setText("Current Date");

        lblLeavesForaMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLeavesForaMonth.setText("Leaves for a Year");

        txtLeavesForaMonthD.setEditable(false);
        txtLeavesForaMonthD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLeavesForaMonthD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLeavesForaMonthDMouseClicked(evt);
            }
        });
        txtLeavesForaMonthD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeavesForaMonthDActionPerformed(evt);
            }
        });
        txtLeavesForaMonthD.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtLeavesForaMonthDPropertyChange(evt);
            }
        });
        txtLeavesForaMonthD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLeavesForaMonthDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLeavesForaMonthDKeyReleased(evt);
            }
        });

        valCkLeavesForaMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        valCkCurrentDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        txtRequiredLeaves.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRequiredLeaves.setText("0");
        txtRequiredLeaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtRequiredLeavesMouseReleased(evt);
            }
        });
        txtRequiredLeaves.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRequiredLeavesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRequiredLeavesKeyTyped(evt);
            }
        });

        txtCurrentDate.setEditable(false);
        txtCurrentDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCurrentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentDateActionPerformed(evt);
            }
        });

        txtApproval.setEditable(false);
        txtApproval.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApprovalActionPerformed(evt);
            }
        });

        lblApproval.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblApproval.setText("Approval");

        javax.swing.GroupLayout pnlSideBLayout = new javax.swing.GroupLayout(pnlSideB);
        pnlSideB.setLayout(pnlSideBLayout);
        pnlSideBLayout.setHorizontalGroup(
            pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideBLayout.createSequentialGroup()
                        .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBLayout.createSequentialGroup()
                                .addComponent(lblRequiredLeaves, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRequiredLeaves))
                            .addGroup(pnlSideBLayout.createSequentialGroup()
                                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLeavesForaMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApproval, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addGroup(pnlSideBLayout.createSequentialGroup()
                                        .addComponent(txtLeavesForaMonthD, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                        .addGap(1, 1, 1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valCkTo)
                            .addComponent(valCkLeavesForaMonth)))
                    .addGroup(pnlSideBLayout.createSequentialGroup()
                        .addComponent(lblCurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCurrentDate, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(valCkCurrentDate)))
                .addGap(42, 42, 42))
        );
        pnlSideBLayout.setVerticalGroup(
            pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRequiredLeaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRequiredLeaves))
                    .addComponent(valCkLeavesForaMonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCurrentDate))
                    .addComponent(valCkCurrentDate))
                .addGap(5, 5, 5)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valCkTo)
                    .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLeavesForaMonth)
                        .addComponent(txtLeavesForaMonthD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApproval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApproval))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLeaveRequirementsLayout = new javax.swing.GroupLayout(pnlLeaveRequirements);
        pnlLeaveRequirements.setLayout(pnlLeaveRequirementsLayout);
        pnlLeaveRequirementsLayout.setHorizontalGroup(
            pnlLeaveRequirementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeaveRequirementsLayout.createSequentialGroup()
                .addComponent(pnlSideA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSideB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLeaveRequirementsLayout.setVerticalGroup(
            pnlLeaveRequirementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeaveRequirementsLayout.createSequentialGroup()
                .addGroup(pnlLeaveRequirementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeaveRequirementsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlSideA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSideB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblLeaveRequirements.setBackground(new java.awt.Color(52, 73, 94));
        tblLeaveRequirements.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblLeaveRequirements.setForeground(new java.awt.Color(255, 255, 255));
        tblLeaveRequirements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Leave Requirement No", "Employee ID", "Date Modified", "Leave Date", "Required Leaves", "No Of Attendance", "Current Date", "Absences", "Leaves For a Month", "Approval"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLeaveRequirements.setGridColor(new java.awt.Color(189, 195, 199));
        tblLeaveRequirements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLeaveRequirementsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLeaveRequirements);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlToolBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLeaveRequirements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDisplayBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDisplayBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOrderBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOrderBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSearchBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSearchIcon)
                        .addGap(0, 0, 0)
                        .addComponent(txtSearchBox)
                        .addGap(0, 0, 0)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlToolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDisplayBy)
                        .addComponent(cmbDisplayBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOrderBy)
                        .addComponent(cmbOrderBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSearchBy)
                        .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSearchIcon)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(pnlLeaveRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        changebtnImage.buttonState(btnAdd, "Add_hov");
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
       changebtnImage.buttonState(btnAdd, "Add_def");
    }//GEN-LAST:event_btnAddMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
       changebtnImage.buttonState(btnUpdate, "Update_hov");
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        changebtnImage.buttonState(btnUpdate, "Update_def");
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        changebtnImage.buttonState(btnDelete, "Delete_hov");
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        changebtnImage.buttonState(btnDelete, "Delete_def");
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        changebtnImage.buttonState(btnClear, "Clear_hov");
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        changebtnImage.buttonState(btnClear, "Clear_def");
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
         changebtnImage.buttonState(btnReport, "Report_hov");
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
         changebtnImage.buttonState(btnReport, "Report_def");
    }//GEN-LAST:event_btnReportMouseExited

    private void txtLeavesForaMonthDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeavesForaMonthDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeavesForaMonthDActionPerformed

    private void txtNoOfAbsencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfAbsencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOfAbsencesActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
       
//        Leave.First();
        
       
       
          
               
           
       if(val.isEmpty(txtNoOfAbsences ,"No Of Absences can't be empty")== true)
       {
           if(val.isNumber(txtNoOfAbsences ,"Insert Valid No Of Absences")== true){
              if(val.isPositive(txtNoOfAbsences ,"Insert Valid No Of Positive Absences")== true)  {
       
        if(val.isEmpty(txtRequiredLeaves ,"Required Leaves can't be empty")== true)
        {
            if(val.isNumber(txtRequiredLeaves ,"Insert Valid Required Leaves")== true){
                if(val.isPositive(txtRequiredLeaves ,"Insert Valid Positive Required Leaves")== true){
        
        if(val.isEmpty(txtLeavesForaMonthD ,"Leaves For Month can't be empty")== true) 
        {
                 if(val.isNumber(txtLeavesForaMonthD ,"Insert Valid Leaves For Month")== true){  
                     if(val.isPositive(txtLeavesForaMonthD ,"Insert Valid Positive Leaves For Month")== true)
                     {
                        int msg = JOptionPane.showConfirmDialog(null, "Do you really want to ADD this record?");
                        if(msg == 0)
                        {
                   
                    Leave.add("leave_requirement");
                    Leave.clear();
                        }
                     }
                 }
                    }
                }
           }
                
       }
       }
           
       }
       }
       
    
     
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
     
           
               
           
       if(val.isEmpty(txtNoOfAbsences ,"No Of Absences can't be empty")== true)
       {
           if(val.isNumber(txtNoOfAbsences ,"Insert Valid No Of Absences")== true){
                if(val.isPositive(txtNoOfAbsences ,"Insert Valid No Of Positive Absences")== true)  {
       
        if(val.isEmpty(txtRequiredLeaves ,"Required Leaves can't be empty")== true)
        {
            if(val.isNumber(txtRequiredLeaves ,"Insert Valid Required Leaves")== true){
              
             if(val.isPositive(txtRequiredLeaves ,"Insert Valid Positive Required Leaves")== true){
        
        if(val.isEmpty(txtLeavesForaMonthD ,"Leaves For Month can't be empty")== true) 
        {
                 if(val.isNumber(txtLeavesForaMonthD ,"Insert Valid Leaves For Month")== true){ 
                     
                      if(val.isPositive(txtLeavesForaMonthD ,"Insert Valid Positive Leaves For Month")== true)
                      {
                        int msg = JOptionPane.showConfirmDialog(null, "Do you really want to UPDATE this record?");
                        if(msg == 0)
                        {
                   
                     Leave.update("leave_requirement");
                    Leave.clear();
                        }
                      }
                 }
                    }
                }
           }
                
       }
       }
           
       }
       }
       
        
      
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void tblLeaveRequirementsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLeaveRequirementsMouseClicked
       Leave.setAll();
       
       
    }//GEN-LAST:event_tblLeaveRequirementsMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
       
//         int msg = JOptionPane.showConfirmDialog(null, "Do you really want to DELETE this record?");
//         
//         if(msg == 0)
//         {
//        
//        Leave.delete("leave_requirement", "Leave Requirement No", Leave.getPrimaryKey(),tblLeaveRequirements);
      //   }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtCurrentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentDateActionPerformed

    private void txtApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApprovalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApprovalActionPerformed

    private void txtNoOfAbsencesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfAbsencesKeyReleased
      
        
    }//GEN-LAST:event_txtNoOfAbsencesKeyReleased

    private void txtLeavesForaMonthDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLeavesForaMonthDKeyReleased
        

    }//GEN-LAST:event_txtLeavesForaMonthDKeyReleased

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
       Leave.clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void txtSearchBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchBoxMouseClicked
        Leave.clear();
    }//GEN-LAST:event_txtSearchBoxMouseClicked

    private void txtSearchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxKeyReleased
        Leave.Modelsearch();
    }//GEN-LAST:event_txtSearchBoxKeyReleased

    private void cmbEmployeeIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEmployeeIDMouseClicked
        // TODO add your handling code here:
      Leave.FindAbsences(cmbEmployeeID.getSelectedItem().toString());
//        Leave.LeaveForaMonth();
        Leave.findNoOfLeaves(cmbEmployeeID.getSelectedItem().toString());
       
    }//GEN-LAST:event_cmbEmployeeIDMouseClicked

    private void cmbEmployeeIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbEmployeeIDKeyReleased
        // TODO add your handling code here:
       // Leave.LeaveForaMonth();
       //Leave.FindAbsences(cmbEmployeeID.getSelectedItem().toString());
         
    }//GEN-LAST:event_cmbEmployeeIDKeyReleased

    private void cmbEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmployeeIDActionPerformed
        // TODO add your handling code here:
         //Leave.LeaveForaMonth();
       //Leave.FindAbsences(cmbEmployeeID.getSelectedItem().toString());
    }//GEN-LAST:event_cmbEmployeeIDActionPerformed

    private void cmbEmployeeIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbEmployeeIDPropertyChange
        // TODO add your handling code here:
        
              
        
       
    }//GEN-LAST:event_cmbEmployeeIDPropertyChange

    private void txtLeavesForaMonthDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLeavesForaMonthDKeyPressed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_txtLeavesForaMonthDKeyPressed

    private void txtLeavesForaMonthDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtLeavesForaMonthDPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtLeavesForaMonthDPropertyChange

    private void txtLeavesForaMonthDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLeavesForaMonthDMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtLeavesForaMonthDMouseClicked

    private void txtRequiredLeavesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequiredLeavesKeyReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtRequiredLeavesKeyReleased

    private void txtRequiredLeavesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRequiredLeavesMouseReleased
        // TODO add your handling code here:
//           String searchApproval = txtNoOfAbsences.getText();
//          int test = parseInt(searchApproval);
//          String S1 = txtLeavesForaMonthD.getText();
//          int test1 =parseInt(S1);
//          String S2= txtRequiredLeaves.getText();
//          int test2 =parseInt(S2);
//       
//       Leave.findApproval(test,test1,test2);
       
    }//GEN-LAST:event_txtRequiredLeavesMouseReleased

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
         //Leave.newupdate("leave_requirement");
//        if(cancel.equals("Not cancel"))
//        {
//            cancel="cancel";
//           
//        }
//        else if(cancel.equals("cancel"))
//        {
//            cancel="Not Cancel";
//        }
//       
//        JOptionPane.showMessageDialog(null,cancel );
            Leave.update("leave_requirement");
            if(flag)
            {
                flag =false;
                 cancel="Not Cancel";
            }
            else
            {
                flag = true;
                cancel="cancel";
            }
           // Leave.update("leave_requirement");
 JOptionPane.showMessageDialog(null,cancel );
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtRequiredLeavesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequiredLeavesKeyTyped
        // TODO add your handling code here:
       // Leave.FindApproval();
    }//GEN-LAST:event_txtRequiredLeavesKeyTyped

    private void btnCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckMouseClicked
        // TODO add your handling code here:
        Leave.FindApproval();
    }//GEN-LAST:event_btnCheckMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
        // TODO add your handling code here:
        Leave.report();
    }//GEN-LAST:event_btnReportMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    public static javax.swing.JButton btnCancel;
    public static javax.swing.JButton btnCheck;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReport;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JComboBox<String> cmbDisplayBy;
    public static javax.swing.JComboBox<String> cmbEmployeeID;
    private javax.swing.JComboBox<String> cmbOrderBy;
    public static javax.swing.JComboBox<String> cmbSearchBy;
    public static com.toedter.calendar.JDateChooser dtpLeaveDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApproval;
    private javax.swing.JLabel lblCurrentDate;
    private javax.swing.JLabel lblDisplayBy;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblLeaveDate;
    private javax.swing.JLabel lblLeaveRecordNo;
    private javax.swing.JLabel lblLeavesForaMonth;
    private javax.swing.JLabel lblNoOfAbsences;
    private javax.swing.JLabel lblOrderBy;
    private javax.swing.JLabel lblRequiredLeaves;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JLabel lblSearchIcon;
    private javax.swing.JPanel pnlLeaveRequirements;
    private javax.swing.JPanel pnlSideA;
    private javax.swing.JPanel pnlSideB;
    private javax.swing.JPanel pnlToolBox;
    public static javax.swing.JTable tblLeaveRequirements;
    public static javax.swing.JTextField txtApproval;
    public static javax.swing.JTextField txtCurrentDate;
    public static javax.swing.JTextField txtLeaveRequirementNo;
    public static javax.swing.JTextField txtLeavesForaMonthD;
    public static javax.swing.JTextField txtNoOfAbsences;
    public static javax.swing.JTextField txtRequiredLeaves;
    public static javax.swing.JTextField txtSearchBox;
    private javax.swing.JLabel valCkApproval;
    private javax.swing.JLabel valCkCurrentDate;
    private javax.swing.JLabel valCkEmployeeID;
    private javax.swing.JLabel valCkLeaveDate;
    private javax.swing.JLabel valCkLeavesForaMonth;
    private javax.swing.JLabel valCkNoOfAbsences;
    private javax.swing.JLabel valCkTo;
    // End of variables declaration//GEN-END:variables
}
