/*
 * Hotel Management System for Pavana Hotel Kochchikade
 * Information Technology Project - 2016
 * Project ID   : ITP_WD_16_B1_06
 * Supervisor   : Mrs. Asanthika Imbulpitiya
 *
 * Student Name : Kaushalya R.U
 * IT Number    : IT14087202
 */
package app.employee_management;

import javax.swing.JOptionPane;
import model.employee_management.Employee_Details_Model;
import model.employee_management.Manage_Employee_Roles_Model;
import model.employee_management.System_Users_Model;
import source.ImageProcessing;
import source.Validation;

/**
 *
 * @author Dhanuka Perera
 */
public class Manage_Employee_Roles_Frames extends javax.swing.JPanel {

     ImageProcessing changebtnImage = new ImageProcessing();
      Validation val = new Validation ();
     
      public Manage_Employee_Roles_Model Role = new Manage_Employee_Roles_Model();
     
    public Manage_Employee_Roles_Frames() {
        initComponents();
        Role.loadTable("manage_employee_roles",tblManageEmployeeRoles);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlToolBox = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        lblDisplayBy = new javax.swing.JLabel();
        cmbDisplayBy = new javax.swing.JComboBox<>();
        lblOrderBy = new javax.swing.JLabel();
        cmbOrderBy = new javax.swing.JComboBox<>();
        lblSearchBy = new javax.swing.JLabel();
        cmbSearchBy = new javax.swing.JComboBox<>();
        lblSearchIcon = new javax.swing.JLabel();
        txtSearchBox = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        pnlManagEmployeeRoles = new javax.swing.JPanel();
        pnlSideA = new javax.swing.JPanel();
        txtEmployeeRole = new javax.swing.JTextField();
        lblEmployeeRole = new javax.swing.JLabel();
        valCkEmployeeRole = new javax.swing.JLabel();
        txtBasicSalary = new javax.swing.JTextField();
        lblBasicSalary = new javax.swing.JLabel();
        valCkHourlyRate = new javax.swing.JLabel();
        lblRecordID = new javax.swing.JLabel();
        txtRecordID = new javax.swing.JTextField();
        pnlSideB = new javax.swing.JPanel();
        lblLeavesForaMonth = new javax.swing.JLabel();
        txtLeavesForaMonth = new javax.swing.JTextField();
        valCkLeavesForaMonth = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbRoleType = new javax.swing.JComboBox<>();
        cmbPositionStatus = new javax.swing.JComboBox<>();
        lblPositionStatus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblManageEmployeeRoles = new javax.swing.JTable();

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));

        pnlToolBox.setBackground(new java.awt.Color(221, 221, 221));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Add_def.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Update_def.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Delete_def.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Clear_def.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Report_def.png"))); // NOI18N
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlToolBoxLayout = new javax.swing.GroupLayout(pnlToolBox);
        pnlToolBox.setLayout(pnlToolBoxLayout);
        pnlToolBoxLayout.setHorizontalGroup(
            pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolBoxLayout.createSequentialGroup()
                .addComponent(btnAdd)
                .addGap(0, 0, 0)
                .addComponent(btnUpdate)
                .addGap(0, 0, 0)
                .addComponent(btnDelete)
                .addGap(0, 0, 0)
                .addComponent(btnClear)
                .addGap(0, 0, 0)
                .addComponent(btnReport)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlToolBoxLayout.setVerticalGroup(
            pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolBoxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        lblDisplayBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDisplayBy.setText("Display By :");

        cmbDisplayBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbDisplayBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblOrderBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrderBy.setText("Order By :");

        cmbOrderBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbOrderBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSearchBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchBy.setText("Search By :");

        cmbSearchBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Record ID", "Employee Role", "Basic Salary", "Role Type", "Position Type", "Leave For a Year", " " }));

        lblSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/searchIcon.png"))); // NOI18N

        txtSearchBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchBox.setText("Search...");
        txtSearchBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchBoxMouseClicked(evt);
            }
        });
        txtSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBoxKeyReleased(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/searchButton.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        pnlManagEmployeeRoles.setBackground(new java.awt.Color(255, 255, 255));
        pnlManagEmployeeRoles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlSideA.setBackground(new java.awt.Color(255, 255, 255));

        txtEmployeeRole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblEmployeeRole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmployeeRole.setText("Employee Role");

        valCkEmployeeRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        txtBasicSalary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblBasicSalary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBasicSalary.setText("Basic Salary");

        valCkHourlyRate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblRecordID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRecordID.setText("Record ID");

        txtRecordID.setEditable(false);

        javax.swing.GroupLayout pnlSideALayout = new javax.swing.GroupLayout(pnlSideA);
        pnlSideA.setLayout(pnlSideALayout);
        pnlSideALayout.setHorizontalGroup(
            pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblEmployeeRole, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(lblBasicSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRecordID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmployeeRole, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(txtBasicSalary)
                    .addComponent(txtRecordID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valCkEmployeeRole)
                    .addComponent(valCkHourlyRate))
                .addGap(42, 42, 42))
        );
        pnlSideALayout.setVerticalGroup(
            pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valCkEmployeeRole)
                    .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRecordID)
                        .addComponent(txtRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmployeeRole))
                    .addComponent(valCkHourlyRate))
                .addGap(4, 4, 4)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBasicSalary))
                .addGap(33, 33, 33))
        );

        pnlSideB.setBackground(new java.awt.Color(255, 255, 255));

        lblLeavesForaMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLeavesForaMonth.setText("Leaves For a Year");

        txtLeavesForaMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        valCkLeavesForaMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Role Type");

        cmbRoleType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbRoleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kitchen", "Administration", "Laundry", "Touring", "Events " }));

        cmbPositionStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbPositionStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanent", "Temporary" }));

        lblPositionStatus.setText("Position Status");

        javax.swing.GroupLayout pnlSideBLayout = new javax.swing.GroupLayout(pnlSideB);
        pnlSideB.setLayout(pnlSideBLayout);
        pnlSideBLayout.setHorizontalGroup(
            pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLeavesForaMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblPositionStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPositionStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLeavesForaMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(cmbRoleType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valCkLeavesForaMonth)
                .addGap(40, 40, 40))
        );
        pnlSideBLayout.setVerticalGroup(
            pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLeavesForaMonth)
                        .addComponent(txtLeavesForaMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valCkLeavesForaMonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbRoleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPositionStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPositionStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlManagEmployeeRolesLayout = new javax.swing.GroupLayout(pnlManagEmployeeRoles);
        pnlManagEmployeeRoles.setLayout(pnlManagEmployeeRolesLayout);
        pnlManagEmployeeRolesLayout.setHorizontalGroup(
            pnlManagEmployeeRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManagEmployeeRolesLayout.createSequentialGroup()
                .addComponent(pnlSideA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSideB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlManagEmployeeRolesLayout.setVerticalGroup(
            pnlManagEmployeeRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlSideA, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tblManageEmployeeRoles.setBackground(new java.awt.Color(52, 73, 97));
        tblManageEmployeeRoles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblManageEmployeeRoles.setForeground(new java.awt.Color(255, 255, 255));
        tblManageEmployeeRoles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Record ID", "Date Modified", "Employee Role", "Basic Salary", "Increment Percentage", "Leaves For Month", "Role Type", "Position Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblManageEmployeeRoles.setGridColor(new java.awt.Color(189, 195, 199));
        tblManageEmployeeRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblManageEmployeeRolesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblManageEmployeeRoles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlToolBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDisplayBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDisplayBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOrderBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOrderBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSearchBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSearchIcon)
                        .addGap(0, 0, 0)
                        .addComponent(txtSearchBox)
                        .addGap(0, 0, 0)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane2)
                    .addComponent(pnlManagEmployeeRoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlToolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDisplayBy)
                        .addComponent(cmbDisplayBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOrderBy)
                        .addComponent(cmbOrderBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSearchBy)
                        .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSearchIcon)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(pnlManagEmployeeRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        changebtnImage.buttonState(btnAdd, "Add_hov");
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
       changebtnImage.buttonState(btnAdd, "Add_def");
    }//GEN-LAST:event_btnAddMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
       changebtnImage.buttonState(btnUpdate, "Update_hov"); 
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
      changebtnImage.buttonState(btnUpdate, "Update_def");  
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        changebtnImage.buttonState(btnDelete, "Delete_hov"); 
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        changebtnImage.buttonState(btnDelete, "Delete_def"); 
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        changebtnImage.buttonState(btnClear, "Clear_hov"); 
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        changebtnImage.buttonState(btnClear, "Clear_def");
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        changebtnImage.buttonState(btnReport, "Report_hov"); 
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        changebtnImage.buttonState(btnReport, "Report_def"); 
    }//GEN-LAST:event_btnReportMouseExited

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked

                
        if(Validation.isEmpty(txtEmployeeRole ,"Role Name can't be empty")== true)  
       {
           if(val.isLetters(txtEmployeeRole ,"Insert Valid Employee Role")== true){
        if(Validation.isEmpty(txtBasicSalary ,"Hourly Rate can't be empty")== true)  
           {
                if(val.isNumber(txtBasicSalary ,"Insert Valid Basic Salary")== true){
                    if(val.isPositive(txtBasicSalary ,"Insert Valid Positive Basic Salary")== true){
                      if(val.NoequalsToZero(txtBasicSalary ,"Insert Valid Basic Salary greater than Zero")== true){
        if(Validation.isEmpty(txtLeavesForaMonth ,"Leave For a month can't be empty")== true)  
            {
                  if(val.isNumber(txtLeavesForaMonth ,"Insert Valid Leave For a month ")== true){
            
                       if(val.isPositive(txtLeavesForaMonth ,"Insert Valid Positive Leave For a month")== true){
                      //if(Validation.isEmpty(txtAllocatedMonthlyHours ,"Allocated Month can't be empty")== true)
                      {
                       // if(val.isNumber(txtAllocatedMonthlyHours ,"Insert Valid Allocated Month ")== true){
                            // if(val.isPositive(txtAllocatedMonthlyHours ,"Insert Valid Positive Allocated Month")== true){
                          int msg = JOptionPane.showConfirmDialog(null, "Do you really want to ADD this record?");
                            if(msg == 0)
                            {
                                 Role.add("manage_employee_roles");
                                 Role.clear();
                            }
                        }
                      }
       }
            }
                }
           }
       }
       }
           
          }  
       }
        
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
       
        if(Validation.isEmpty(txtEmployeeRole ,"Role Name can't be empty")== true)  
       {
           if(val.isLetters(txtEmployeeRole ,"Insert Valid Employee Role")== true){
        if(Validation.isEmpty(txtBasicSalary ,"Hourly Rate can't be empty")== true)  
           {
                if(val.isNumber(txtBasicSalary ,"Insert Valid Hourly Rate")== true){
        if(Validation.isEmpty(txtLeavesForaMonth ,"Leave For a month can't be empty")== true)  
            {
                  if(val.isNumber(txtLeavesForaMonth ,"Insert Valid Leave For a month ")== true){
            
                      //if(Validation.isEmpty(txtAllocatedMonthlyHours ,"Allocated Month can't be empty")== true)
                      {
                        //if(val.isNumber(txtAllocatedMonthlyHours ,"Insert Valid Allocated Month ")== true)
                        {
                      
                          int msg = JOptionPane.showConfirmDialog(null, "Do you really want to UPDATE this record?");
                            if(msg == 0)
                            {
                                 Role.update("manage_employee_roles");
                                 Role.clear();
                            }
                        }
                      }
       }
            }
                }
           }
       }
       }
        
      
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        
          int msg = JOptionPane.showConfirmDialog(null, "Do you really want to DELETE this record?");
            if(msg == 0)
            {
                 Role.delete("manage_employee_roles", "Record ID", Role.getPrimaryKey(),tblManageEmployeeRoles);
            }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void tblManageEmployeeRolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblManageEmployeeRolesMouseClicked
        Role.setAll();
    }//GEN-LAST:event_tblManageEmployeeRolesMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
       Role.clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void txtSearchBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchBoxMouseClicked
       Role.clear();
    }//GEN-LAST:event_txtSearchBoxMouseClicked

    private void txtSearchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxKeyReleased
       Role.Modelsearch();
    }//GEN-LAST:event_txtSearchBoxKeyReleased

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        Role.Modelsearch();
    }//GEN-LAST:event_btnSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReport;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JComboBox<String> cmbDisplayBy;
    private javax.swing.JComboBox<String> cmbOrderBy;
    public static javax.swing.JComboBox<String> cmbPositionStatus;
    public static javax.swing.JComboBox<String> cmbRoleType;
    public static javax.swing.JComboBox<String> cmbSearchBy;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBasicSalary;
    private javax.swing.JLabel lblDisplayBy;
    private javax.swing.JLabel lblEmployeeRole;
    private javax.swing.JLabel lblLeavesForaMonth;
    private javax.swing.JLabel lblOrderBy;
    private javax.swing.JLabel lblPositionStatus;
    private javax.swing.JLabel lblRecordID;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JLabel lblSearchIcon;
    private javax.swing.JPanel pnlManagEmployeeRoles;
    private javax.swing.JPanel pnlSideA;
    private javax.swing.JPanel pnlSideB;
    private javax.swing.JPanel pnlToolBox;
    public static javax.swing.JTable tblManageEmployeeRoles;
    public static javax.swing.JTextField txtBasicSalary;
    public static javax.swing.JTextField txtEmployeeRole;
    public static javax.swing.JTextField txtLeavesForaMonth;
    public static javax.swing.JTextField txtRecordID;
    public static javax.swing.JTextField txtSearchBox;
    private javax.swing.JLabel valCkEmployeeRole;
    private javax.swing.JLabel valCkHourlyRate;
    private javax.swing.JLabel valCkLeavesForaMonth;
    // End of variables declaration//GEN-END:variables
}
