/*
 * Hotel Management System for Pavana Hotel Kochchikade
 * Information Technology Project - 2016
 * Project ID   : ITP_WD_16_B1_06
 * Supervisor   : Mrs. Asanthika Imbulpitiya
 *
 * Student Name : Kaushalya R.U
 * IT Number    : IT14087202
 */
package app.employee_management;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.employee_management.Shift_Management_Model;
import source.ImageProcessing;
import source.Validation;

/**
 *
 * @author Dhanuka Perera
 */
public class Shift_Management_Frame extends javax.swing.JPanel {

       ImageProcessing changebtnImage = new ImageProcessing();
       Validation val = new Validation ();
      Shift_Management_Model Shift = new Shift_Management_Model();
    public Shift_Management_Frame() {
        initComponents();
         Shift.LoadEmployeeID2();
         
         Shift.loadTable("shift_management",tblShiftManagement);
        //Shift.loadListFromDB("Employee ID", "employee_details", cmbEmployeeID);
        //Shift.gettingLeaveDetails();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlToolBox = new javax.swing.JPanel();
        btnAssignShift = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        lblDisplayBy = new javax.swing.JLabel();
        cmbDisplayBy = new javax.swing.JComboBox<>();
        lblOrderBy = new javax.swing.JLabel();
        cmbOrderBy = new javax.swing.JComboBox<>();
        lblSearchBy = new javax.swing.JLabel();
        cmbSearchBy = new javax.swing.JComboBox<>();
        lblSearchIcon = new javax.swing.JLabel();
        txtSearchBox = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        pnlShiftManagement = new javax.swing.JPanel();
        pnlSideA = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblShiftRecordID = new javax.swing.JLabel();
        txtShiftRecordID = new javax.swing.JTextField();
        lblEmployeeID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        lblDepartment = new javax.swing.JLabel();
        txtLeaveDetails = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lblLeaveDetails = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbEmployeeID = new javax.swing.JComboBox<>();
        cmbShiftTime = new javax.swing.JComboBox<>();
        lblShiftTime = new javax.swing.JLabel();
        lblEventDetails = new javax.swing.JLabel();
        txtEventDetails = new javax.swing.JTextField();
        pnlSideB = new javax.swing.JPanel();
        jCalShiftDate = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShiftManagement = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlToolBox.setBackground(new java.awt.Color(221, 221, 221));

        btnAssignShift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Assign_Shift_def.png"))); // NOI18N
        btnAssignShift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAssignShiftMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssignShiftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssignShiftMouseExited(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Update_def.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Delete_def.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Clear_def.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Report_def.png"))); // NOI18N
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlToolBoxLayout = new javax.swing.GroupLayout(pnlToolBox);
        pnlToolBox.setLayout(pnlToolBoxLayout);
        pnlToolBoxLayout.setHorizontalGroup(
            pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolBoxLayout.createSequentialGroup()
                .addComponent(btnAssignShift)
                .addGap(0, 0, 0)
                .addComponent(btnUpdate)
                .addGap(0, 0, 0)
                .addComponent(btnDelete)
                .addGap(0, 0, 0)
                .addComponent(btnClear)
                .addGap(0, 0, 0)
                .addComponent(btnReport)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlToolBoxLayout.setVerticalGroup(
            pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolBoxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssignShift, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        lblDisplayBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDisplayBy.setText("Display By :");

        cmbDisplayBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblOrderBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrderBy.setText("Order By :");

        cmbOrderBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblSearchBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchBy.setText("Search By :");

        cmbSearchBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shift Record ID", "Employee ID", "Name", "Department", "Shift Date", "Shift Time", "Event Details", "Leave Details", " " }));

        lblSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/searchIcon.png"))); // NOI18N

        txtSearchBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchBox.setText("Search...");
        txtSearchBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchBoxMouseClicked(evt);
            }
        });
        txtSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchBoxActionPerformed(evt);
            }
        });
        txtSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBoxKeyReleased(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/searchButton.png"))); // NOI18N
        btnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnSearchKeyReleased(evt);
            }
        });

        pnlShiftManagement.setBackground(new java.awt.Color(255, 255, 255));
        pnlShiftManagement.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shift Management", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        pnlSideA.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblShiftRecordID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblShiftRecordID.setText("Shift Record ID");

        txtShiftRecordID.setEditable(false);
        txtShiftRecordID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmployeeID.setText("Employee ID");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblName.setText("Name");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        cmbDepartment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurant", "Hotel", "Laundry", " " }));

        lblDepartment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDepartment.setText("Department");

        txtLeaveDetails.setEditable(false);
        txtLeaveDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblLeaveDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLeaveDetails.setText("Leave Details");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbEmployeeID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEmployeeID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbEmployeeIDMouseClicked(evt);
            }
        });
        cmbEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmployeeIDActionPerformed(evt);
            }
        });
        cmbEmployeeID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbEmployeeIDPropertyChange(evt);
            }
        });

        cmbShiftTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbShiftTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning - (7.00am-3.00pm)", "Day - (3.00pm-11pm)", "Night - (11.00pm-7.00am)" }));

        lblShiftTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblShiftTime.setText("Shift Time");

        lblEventDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEventDetails.setText("Event Details");

        txtEventDetails.setEditable(false);
        txtEventDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEventDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEventDetailsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSideALayout = new javax.swing.GroupLayout(pnlSideA);
        pnlSideA.setLayout(pnlSideALayout);
        pnlSideALayout.setHorizontalGroup(
            pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSideALayout.createSequentialGroup()
                                .addComponent(lblShiftTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(501, 501, 501))
                            .addGroup(pnlSideALayout.createSequentialGroup()
                                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSideALayout.createSequentialGroup()
                                        .addComponent(lblDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(pnlSideALayout.createSequentialGroup()
                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtName))
                                    .addGroup(pnlSideALayout.createSequentialGroup()
                                        .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbEmployeeID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(pnlSideALayout.createSequentialGroup()
                                        .addComponent(lblShiftRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtShiftRecordID)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideALayout.createSequentialGroup()
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSideALayout.createSequentialGroup()
                                .addComponent(lblEventDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEventDetails))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSideALayout.createSequentialGroup()
                                .addComponent(lblLeaveDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbShiftTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLeaveDetails))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(171, 171, 171))))
        );
        pnlSideALayout.setVerticalGroup(
            pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtShiftRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblShiftRecordID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployeeID)
                    .addComponent(cmbEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDepartment)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbShiftTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblShiftTime)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeaveDetails)
                    .addComponent(txtLeaveDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEventDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEventDetails))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlSideB.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlSideBLayout = new javax.swing.GroupLayout(pnlSideB);
        pnlSideB.setLayout(pnlSideBLayout);
        pnlSideBLayout.setHorizontalGroup(
            pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jCalShiftDate, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnlSideBLayout.setVerticalGroup(
            pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jCalShiftDate, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlShiftManagementLayout = new javax.swing.GroupLayout(pnlShiftManagement);
        pnlShiftManagement.setLayout(pnlShiftManagementLayout);
        pnlShiftManagementLayout.setHorizontalGroup(
            pnlShiftManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShiftManagementLayout.createSequentialGroup()
                .addComponent(pnlSideA, javax.swing.GroupLayout.PREFERRED_SIZE, 499, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSideB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlShiftManagementLayout.setVerticalGroup(
            pnlShiftManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShiftManagementLayout.createSequentialGroup()
                .addGroup(pnlShiftManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSideA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSideB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblShiftManagement.setBackground(new java.awt.Color(52, 73, 94));
        tblShiftManagement.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblShiftManagement.setForeground(new java.awt.Color(255, 255, 255));
        tblShiftManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Shift Record No", "Employee ID", "Name", "Department", "Shift Date", "Shift Time", "Event Details", "Leave Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblShiftManagement.setGridColor(new java.awt.Color(189, 195, 199));
        tblShiftManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShiftManagementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShiftManagement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlToolBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDisplayBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDisplayBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOrderBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOrderBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSearchBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSearchIcon)
                        .addGap(0, 0, 0)
                        .addComponent(txtSearchBox, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1)
                    .addComponent(pnlShiftManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlToolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDisplayBy)
                        .addComponent(cmbDisplayBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOrderBy)
                        .addComponent(cmbOrderBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSearchBy)
                        .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSearchIcon)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(pnlShiftManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignShiftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignShiftMouseEntered
       changebtnImage.buttonState(btnAssignShift, "Assign_Shift_hov");
    }//GEN-LAST:event_btnAssignShiftMouseEntered

    private void btnAssignShiftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignShiftMouseExited
       changebtnImage.buttonState(btnAssignShift, "Assign_Shift_def"); 
    }//GEN-LAST:event_btnAssignShiftMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        changebtnImage.buttonState(btnUpdate, "Update_hov");
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        changebtnImage.buttonState(btnUpdate, "Update_def");
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        changebtnImage.buttonState(btnDelete, "Delete_hov");
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        changebtnImage.buttonState(btnDelete, "Delete_def");
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
         changebtnImage.buttonState(btnClear, "Clear_hov");
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        changebtnImage.buttonState(btnClear, "Clear_def");
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        changebtnImage.buttonState(btnReport, "Report_hov");
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
         changebtnImage.buttonState(btnReport, "Report_def");
    }//GEN-LAST:event_btnReportMouseExited

    private void txtSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchBoxActionPerformed

    private void cmbEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmployeeIDActionPerformed
        // TODO add your handling code here:
         //Shift.findName(cmbEmployeeID.getSelectedItem().toString());
         
         //String id2= cmbEmployeeID.getSelectedItem().toString();
          
          //Shift.loadListFromDB("Employee ID", "employee_details", cmbEmployeeID);
          //cmbEmployeeID.setSelectedItem(id2);
          
          //Shift.LoadEmployeeID2();
          //Shift.gettingLeaveDetails();
          //String id = cmbEmployeeID.getSelectedItem().toString();
         // Shift.loadListFromDB("Employee ID", "employee_details", cmbEmployeeID);
         // cmbEmployeeID.setSelectedItem(id);
          
    }//GEN-LAST:event_cmbEmployeeIDActionPerformed

    private void btnAssignShiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignShiftMouseClicked
        // TODO add your handling code here:
        int msg = JOptionPane.showConfirmDialog(null, "Do you really want to ADD this record?");
                        if(msg == 0){
        Shift.add("shift_management");
        Shift.Clear();}
       
    }//GEN-LAST:event_btnAssignShiftMouseClicked

    private void cmbEmployeeIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEmployeeIDMouseClicked
        // TODO add your handling code here:
        Shift.findName(cmbEmployeeID.getSelectedItem().toString());
        Shift.gettingLeaveDetails();
       // Shift.LoadLeaves();
    }//GEN-LAST:event_cmbEmployeeIDMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
           int msg = JOptionPane.showConfirmDialog(null, "Do you really want to DELETE this record?");
             
            if (msg == 0) 
            {
                 Shift.delete("shift_management", "Shift Record No", Shift.getPrimaryKey(),tblShiftManagement);
                
            }
        
       
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        int msg = JOptionPane.showConfirmDialog(null, "Do you really want to UPDATE this record?");
                        if(msg == 0){
        Shift.update("shift_management");
        Shift.Clear();
                        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        Shift.Clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void tblShiftManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShiftManagementMouseClicked
      // Shift.setShiftTimes1();
      Shift.setAll();
      Shift.setEmployeeID();
    }//GEN-LAST:event_tblShiftManagementMouseClicked

    private void txtEventDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEventDetailsMouseClicked
        // TODO add your handling code here:
        Shift.LoadLeaves();
    }//GEN-LAST:event_txtEventDetailsMouseClicked

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
        // TODO add your handling code here:
        //String d ;//= jCalShiftDate.getDate().toGMTString();
//         DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
//        java.util.Date dateobj =jCalShiftDate.getDate();
//        txtName.setText(df.format(dateobj));       
        //txtName.setText(d);
    }//GEN-LAST:event_btnReportMouseClicked

    private void cmbEmployeeIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbEmployeeIDPropertyChange
        // TODO add your handling code here:
//        Shift.findName(cmbEmployeeID.getSelectedItem().toString());
//        Shift.gettingLeaveDetails();
    }//GEN-LAST:event_cmbEmployeeIDPropertyChange

    private void txtSearchBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchBoxMouseClicked
        // TODO add your handling code here:
        Shift.Clear();
    }//GEN-LAST:event_txtSearchBoxMouseClicked

    private void btnSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSearchKeyReleased
        // TODO add your handling code here:
        Shift.Modelsearch();
    }//GEN-LAST:event_btnSearchKeyReleased

    private void txtSearchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxKeyReleased
        // TODO add your handling code here:
        Shift.Modelsearch();
    }//GEN-LAST:event_txtSearchBoxKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAssignShift;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReport;
    public static javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnUpdate;
    public static javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbDisplayBy;
    public static javax.swing.JComboBox<String> cmbEmployeeID;
    private javax.swing.JComboBox<String> cmbOrderBy;
    public static javax.swing.JComboBox<String> cmbSearchBy;
    public static javax.swing.JComboBox<String> cmbShiftTime;
    public static com.toedter.calendar.JCalendar jCalShiftDate;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDisplayBy;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEventDetails;
    private javax.swing.JLabel lblLeaveDetails;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrderBy;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JLabel lblSearchIcon;
    private javax.swing.JLabel lblShiftRecordID;
    private javax.swing.JLabel lblShiftTime;
    private javax.swing.JPanel pnlShiftManagement;
    private javax.swing.JPanel pnlSideA;
    private javax.swing.JPanel pnlSideB;
    private javax.swing.JPanel pnlToolBox;
    public static javax.swing.JTable tblShiftManagement;
    public static javax.swing.JTextField txtEventDetails;
    public static javax.swing.JTextField txtLeaveDetails;
    public static javax.swing.JTextField txtName;
    public static javax.swing.JTextField txtSearchBox;
    public static javax.swing.JTextField txtShiftRecordID;
    // End of variables declaration//GEN-END:variables
}
