/*
 * Hotel Management System for Pavana Hotel Kochchikade
 * Information Technology Project - 2016
 * Project ID   : ITP_WD_16_B1_06
 * Supervisor   : Mrs. Asanthika Imbulpitiya
 *
 * Student Name : Rathnayaka W.R.A.C.J   
 * IT Number    : IT14036644
*/
package app.finance_management;

import app.event_handling.Bill_Frame;
import app.laundry_and_room_service.Finance_Frame;
import app.restaurant_management.Restaurant_Bill_Frames;
//import app.restaurant_management.Dine_In_Bill_Frame;
import javax.swing.JOptionPane;
import source.ImageProcessing;
import model.finance_management.Incomes_Management_Model;
import source.Validation;


/**
 *
 * @author Dhanuka Perera
 */
public class Incomes_Management_Frame extends javax.swing.JPanel {

    ImageProcessing changebtnImage = new ImageProcessing();
    public Incomes_Management_Model obj = new Incomes_Management_Model();
    public Restaurant_Bill_Frames obj1 = new Restaurant_Bill_Frames();
    
    Validation validate = new Validation();
   
    public Incomes_Management_Frame() {
        initComponents();
         obj.loadTable("incomes_management",tblIncomes);
    }
     
   
    
   
       
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        cmbBarchart = new javax.swing.JComboBox<>();
        lblDepartment1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbTimePeriod = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbSearchBy = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncomes = new javax.swing.JTable();
        panelchart = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIncome = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        txtIncome = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        lblIncomeNo = new javax.swing.JLabel();
        txtIncomeNo = new javax.swing.JTextField();

        jLabel7.setText("jLabel7");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Add_def.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Delete_def.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Update_def.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Clear_def.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Report_def.png"))); // NOI18N
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });

        lblDepartment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDepartment.setText("Department :");

        cmbDepartment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Room Reservation", "Restaurant ", "Events", "Laundry and Room Service", "Transport and Tour Management", "Other", " " }));
        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });

        cmbBarchart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bar chart", "Pie chart", "Line chart", " " }));

        lblDepartment1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDepartment1.setText("Chart Type :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Time Period :");

        cmbTimePeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Monthly", "Annualy" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAdd)
                .addGap(0, 0, 0)
                .addComponent(btnUpdate)
                .addGap(0, 0, 0)
                .addComponent(btnDelete)
                .addGap(0, 0, 0)
                .addComponent(btnClear)
                .addGap(0, 0, 0)
                .addComponent(btnReport)
                .addGap(18, 18, 18)
                .addComponent(lblDepartment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDepartment1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBarchart, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTimePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdd)
            .addComponent(btnDelete)
            .addComponent(btnUpdate)
            .addComponent(btnClear)
            .addComponent(btnReport)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBarchart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartment1)
                    .addComponent(jLabel8)
                    .addComponent(cmbTimePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Search By :");

        cmbSearchBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Income ID", "Date Modified", "Income", "Amount", "Department", " " }));
        cmbSearchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchByActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/searchIcon.png"))); // NOI18N

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.setText("Search...");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/searchButton.png"))); // NOI18N

        tblIncomes.setBackground(new java.awt.Color(52, 73, 94));
        tblIncomes.setForeground(new java.awt.Color(255, 255, 255));
        tblIncomes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Income No", "Date Modified", "Income", "Amount"
            }
        ));
        tblIncomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIncomesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIncomes);

        panelchart.setLayout(new java.awt.BorderLayout());

        lblIncome.setText("Income");

        lblAmount.setText("Amount");

        txtIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIncomeActionPerformed(evt);
            }
        });

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        lblIncomeNo.setText("Income No");

        txtIncomeNo.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIncomeNo)
                .addGap(18, 18, 18)
                .addComponent(txtIncomeNo)
                .addGap(18, 18, 18)
                .addComponent(lblIncome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAmount)
                .addGap(18, 18, 18)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIncome)
                    .addComponent(lblAmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIncomeNo)
                    .addComponent(txtIncomeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panelchart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(txtSearch)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5))
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelchart, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        changebtnImage.buttonState(btnAdd, "Add_hov");
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        changebtnImage.buttonState(btnAdd, "Add_def");
    }//GEN-LAST:event_btnAddMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        changebtnImage.buttonState(btnUpdate, "Update_hov");
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        changebtnImage.buttonState(btnUpdate, "Update_def");
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        changebtnImage.buttonState(btnDelete, "Delete_hov");
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
         changebtnImage.buttonState(btnDelete, "Delete_def");
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        changebtnImage.buttonState(btnClear, "Clear_hov");
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        changebtnImage.buttonState(btnClear, "Clear_def");
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        changebtnImage.buttonState(btnReport, "Report_hov");
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        changebtnImage.buttonState(btnReport, "Report_def");
    }//GEN-LAST:event_btnReportMouseExited

    private void cmbSearchByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchByActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartmentActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked

      if(Validation.isEmpty(txtIncome, "Income can't be empty")==true)
      {
          if(Validation.isEmpty(txtAmount, "Amount can't be empty")==true)
          {
             int msg = JOptionPane.showConfirmDialog(null,"Do you really want to Add a new record?");
             
             if(msg==0)
             {
                 if(Validation.isNumber(txtAmount, "Invalid Data")==true){
                     if(Validation.isPositive(txtAmount, "Invalid Data")==true){
                        
                       obj.add("incomes_management");
                       
                       JOptionPane.showMessageDialog(null, "Record Added Successfully");
                     }
                 }
             }
          }
      }
     //  obj.danuka();
     
      clear();
      
     
      
    
        
    }//GEN-LAST:event_btnAddMouseClicked

    private void txtIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIncomeActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
       
        if(Validation.isEmpty(txtIncome, "Income can't be empty")==true)
      {
          if(Validation.isEmpty(txtAmount, "Amount can't be empty")==true)
          {
             int msg = JOptionPane.showConfirmDialog(null,"Do you really want to UPDATE this record?");
             
             if(msg==0)
             {
                  if(Validation.isNumber(txtAmount, "Invalid Data")==true){
                        if(Validation.isPositive(txtAmount, "Invalid Data")==true){
                    obj.update("incomes_management");
                    JOptionPane.showMessageDialog(null, "Record Updated Successfully");
                        }
                  }
             }
          }
      }
      clear();
        
        
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        
          
        if(Validation.isEmpty(txtIncome, "Income can't be empty")==true)
      {
          if(Validation.isEmpty(txtAmount, "Amount can't be empty")==true)
          {
             int msg = JOptionPane.showConfirmDialog(null,"Do you really want to DELETE this record?");
             
             if(msg==0)
             {
                 int selectedrow = tblIncomes.getSelectedRow();
                 String incomecolumn = (String) tblIncomes.getValueAt(selectedrow, 2);
                 obj.delete("incomes_management", "Income ID", obj.getPrimaryKey(),tblIncomes);
                 
//                 //kabba
                 if(incomecolumn.startsWith("BILL")){
                     //System.out.println("chami");
                    
                     //obj1.delete("restaurant_bill", "Number", obj.getPrimaryKey(),Restaurant_Bill_Frames.tblTempBill);  
                  //    obj1.deleterow("restaurant_customer_issue_bill");
                 }
////                 //kabba
//                 else if(incomecolumn.startsWith("")){
//                     obj.delete("takeoutorders", "Number", obj.getPrimaryKey(),Dine_In_Bill_Frame.jTable1);
//                 }
//                 //saumya
//                 else if(incomecolumn.startsWith("")){
//                     obj.delete("event_bills", "Invoice No", obj.getPrimaryKey(),Bill_Frame.tblBill);
//                 }
//                 //kibula
//                 else if(incomecolumn.startsWith("")){
//                     obj.delete("finance", "Finance ID", obj.getPrimaryKey(),Finance_Frame.tblFinance);
//                 }
//                 //khan
//                 else if(incomecolumn.startsWith("")){
//                     obj.delete("transport_details", "Transport ID", obj.getPrimaryKey(),Transport_Details_Frame.tblTransport_Details_Frame);
//                 }
//                 //danuka
//                 else if(incomecolumn.startsWith("")){
//                     obj.delete("", "Transport ID", obj.getPrimaryKey(),Transport_Details_Frame.tblTransport_Details_Frame);
//                 }
//                 
                 JOptionPane.showMessageDialog(null, "Record Deleted Successfully");
//                
                 
                   
             }
          }
      }
        clear();
        
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void tblIncomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIncomesMouseClicked
        obj.setAll();
    }//GEN-LAST:event_tblIncomesMouseClicked

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked

        obj.zeroincome();
      //  obj.report();
        obj.charts();
        
    }//GEN-LAST:event_btnReportMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        clear();
       
    }//GEN-LAST:event_btnClearMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        
        obj.Modelsearch();
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        clear();
    }//GEN-LAST:event_txtSearchMouseClicked
    public void clear(){
       txtAmount.setText("");
       txtIncome.setText(""); 
       txtSearch.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReport;
    private javax.swing.JLabel btnUpdate;
    public static javax.swing.JComboBox<String> cmbBarchart;
    public static javax.swing.JComboBox<String> cmbDepartment;
    public static javax.swing.JComboBox<String> cmbSearchBy;
    public static javax.swing.JComboBox<String> cmbTimePeriod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartment1;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblIncomeNo;
    public static javax.swing.JPanel panelchart;
    public static javax.swing.JTable tblIncomes;
    public static javax.swing.JTextField txtAmount;
    public static javax.swing.JTextField txtIncome;
    public static javax.swing.JTextField txtIncomeNo;
    public static javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
