/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

/**
 *
 * @author Dhanuka Perera
 */
public class Statusbar extends javax.swing.JPanel {

    /**
     * Creates new form Statusbar
     */
    
    Connection con = null; 
    PreparedStatement pst = null;  
    ResultSet rs = null;
    
    public Statusbar() {
        initComponents();
        date_time() ;
        //checkConnection();
    }
    
    /*public void checkConnection()
    {
        new Thread(() -> {
            {
                if(con == null)
                {
                    System.out.println("Connection Fail");
                }
                    
            }
        }).start();
    }
    */
     public final void date_time() 
     {
        String currentTime;
        java.util.Date date = new java.util.Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd-EEEEE");
        currentTime =sdf.format(date);

        new Thread(() -> {
            while (true) {
                java.util.Date d = new java.util.Date();
                SimpleDateFormat sdf1 = new SimpleDateFormat("hh.mm.ss aa");
                lblDateAndTime.setText(currentTime + " | "+ sdf1.format(d));
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStatusBar = new javax.swing.JPanel();
        lblConnectionType = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDateAndTime = new javax.swing.JLabel();

        setBackground(new java.awt.Color(32, 32, 47));

        pnlStatusBar.setBackground(new java.awt.Color(32, 32, 47));

        lblConnectionType.setFont(new java.awt.Font("Myriad Web Pro", 0, 12)); // NOI18N
        lblConnectionType.setForeground(new java.awt.Color(255, 255, 255));
        lblConnectionType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/database_conection.png"))); // NOI18N
        lblConnectionType.setText("Connection Sucessful !");

        lblStatus.setFont(new java.awt.Font("Myriad Web Pro", 0, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("| No Status");

        lblDateAndTime.setFont(new java.awt.Font("Myriad Web Pro", 0, 12)); // NOI18N
        lblDateAndTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateAndTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDateAndTime.setText("Time | Date");

        javax.swing.GroupLayout pnlStatusBarLayout = new javax.swing.GroupLayout(pnlStatusBar);
        pnlStatusBar.setLayout(pnlStatusBarLayout);
        pnlStatusBarLayout.setHorizontalGroup(
            pnlStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConnectionType)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(lblDateAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStatusBarLayout.setVerticalGroup(
            pnlStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConnectionType)
                    .addComponent(lblStatus)
                    .addComponent(lblDateAndTime)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel lblConnectionType;
    private javax.swing.JLabel lblDateAndTime;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlStatusBar;
    // End of variables declaration//GEN-END:variables
}
