/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.event_handling;

import model.event_handling.Venue_Booking_Model;
import source.ImageProcessing;
import source.Validation;

/**
 *
 * @author Dhanuka Perera
 */
public class Venue_Booking_Frame extends javax.swing.JPanel {
    
    Venue_Booking_Model obj = new Venue_Booking_Model ();
    
    Validation itp=new Validation();
    
    public Venue_Booking_Frame ()
    {
        initComponents();
        obj.MenuNo();
       
        
        
    }
    
    ImageProcessing changebtnname = new ImageProcessing();

    /**
     * Creates new form Venue_Booking_Frame
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        M = new javax.swing.JPanel();
        pnlBookingDetails = new javax.swing.JPanel();
        pnlSidea = new javax.swing.JPanel();
        lblBookingNo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblTotalNoofGuests = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtTotalNoOfGuest = new javax.swing.JTextField();
        txtBookingNo = new javax.swing.JTextField();
        cmbEndTime = new javax.swing.JComboBox<>();
        cmbStartTime = new javax.swing.JComboBox<>();
        pnlSideb = new javax.swing.JPanel();
        lblFunctionType = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblAdvance = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cmbFunctionType = new javax.swing.JComboBox<>();
        txtAdvance = new javax.swing.JTextField();
        lblMenuPackageNo = new javax.swing.JLabel();
        cmbMenuNo = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        pnlCustomerInformation = new javax.swing.JPanel();
        pnlSideA = new javax.swing.JPanel();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomerNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlSideB = new javax.swing.JPanel();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        pnlToolBox = new javax.swing.JPanel();
        btnGenerateNewGuestId = new javax.swing.JLabel();
        btnMakeBooking = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmenu = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        M.setBackground(new java.awt.Color(255, 255, 255));

        pnlBookingDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlBookingDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Booking Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlBookingDetails.setPreferredSize(new java.awt.Dimension(1000, 205));

        pnlSidea.setBackground(new java.awt.Color(255, 255, 255));
        pnlSidea.setPreferredSize(new java.awt.Dimension(500, 100));

        lblBookingNo.setText("Booking No");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblTotalNoofGuests.setText("Total No of Guests");

        lblStartTime.setText("Start Time");

        lblEndTime.setText("End Time");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        txtTotalNoOfGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalNoOfGuestActionPerformed(evt);
            }
        });

        txtBookingNo.setEditable(false);
        txtBookingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookingNoActionPerformed(evt);
            }
        });

        cmbEndTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 a.m", "11 p.m" }));
        cmbEndTime.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbEndTimePropertyChange(evt);
            }
        });

        cmbStartTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9 a.m", "7 p.m" }));
        cmbStartTime.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbStartTimePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlSideaLayout = new javax.swing.GroupLayout(pnlSidea);
        pnlSidea.setLayout(pnlSideaLayout);
        pnlSideaLayout.setHorizontalGroup(
            pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideaLayout.createSequentialGroup()
                        .addComponent(lblBookingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBookingNo, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(pnlSideaLayout.createSequentialGroup()
                        .addComponent(lblTotalNoofGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalNoOfGuest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(pnlSideaLayout.createSequentialGroup()
                        .addComponent(lblStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStartTime, 0, 378, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26))
                    .addGroup(pnlSideaLayout.createSequentialGroup()
                        .addComponent(lblEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEndTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)))
                .addGap(42, 42, 42))
        );
        pnlSideaLayout.setVerticalGroup(
            pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideaLayout.createSequentialGroup()
                        .addGroup(pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSideaLayout.createSequentialGroup()
                                .addGroup(pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBookingNo)
                                    .addComponent(jLabel21)
                                    .addComponent(txtBookingNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotalNoofGuests)
                                    .addComponent(txtTotalNoOfGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSideaLayout.createSequentialGroup()
                                .addComponent(lblStartTime)
                                .addGap(6, 6, 6))
                            .addComponent(cmbStartTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEndTime)
                        .addComponent(cmbEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSideb.setBackground(new java.awt.Color(255, 255, 255));
        pnlSideb.setPreferredSize(new java.awt.Dimension(500, 100));

        lblFunctionType.setText("Function Type");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblAdvance.setText("Advance");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblDate.setText("Date");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        cmbFunctionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wedding", "Birthday Party", "Other" }));

        txtAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdvanceActionPerformed(evt);
            }
        });

        lblMenuPackageNo.setText("Menu Package No");

        cmbMenuNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M01", "M02", "M03", "Customize Menu" }));
        cmbMenuNo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbMenuNoPropertyChange(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSidebLayout = new javax.swing.GroupLayout(pnlSideb);
        pnlSideb.setLayout(pnlSidebLayout);
        pnlSidebLayout.setHorizontalGroup(
            pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSidebLayout.createSequentialGroup()
                        .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAdvance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFunctionType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdvance)
                            .addComponent(cmbFunctionType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebLayout.createSequentialGroup()
                        .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMenuPackageNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMenuNo, 0, 418, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(2, 2, 2)))
                .addGap(24, 24, 24))
        );
        pnlSidebLayout.setVerticalGroup(
            pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addGap(9, 9, 9)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFunctionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFunctionType)))
                .addGap(6, 6, 6)
                .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdvance)
                    .addComponent(txtAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSidebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenuPackageNo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbMenuNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBookingDetailsLayout = new javax.swing.GroupLayout(pnlBookingDetails);
        pnlBookingDetails.setLayout(pnlBookingDetailsLayout);
        pnlBookingDetailsLayout.setHorizontalGroup(
            pnlBookingDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookingDetailsLayout.createSequentialGroup()
                .addComponent(pnlSidea, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSideb, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
        );
        pnlBookingDetailsLayout.setVerticalGroup(
            pnlBookingDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookingDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBookingDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlSideb, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(pnlSidea, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pnlCustomerInformation.setBackground(new java.awt.Color(255, 255, 255));
        pnlCustomerInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Customer Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlCustomerInformation.setPreferredSize(new java.awt.Dimension(1000, 205));

        pnlSideA.setBackground(new java.awt.Color(255, 255, 255));
        pnlSideA.setPreferredSize(new java.awt.Dimension(500, 100));

        lblCustomerID.setText("Customer ID");

        txtCustomerNo.setEditable(false);
        txtCustomerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNoActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblFirstName.setText("First Name");

        lblContactNumber.setText("Contact Number");

        lblNIC.setText("NIC");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        javax.swing.GroupLayout pnlSideALayout = new javax.swing.GroupLayout(pnlSideA);
        pnlSideA.setLayout(pnlSideALayout);
        pnlSideALayout.setHorizontalGroup(
            pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addComponent(lblCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContactNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addComponent(lblNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNIC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addGap(42, 42, 42))
        );
        pnlSideALayout.setVerticalGroup(
            pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideALayout.createSequentialGroup()
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSideALayout.createSequentialGroup()
                                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCustomerID)
                                    .addComponent(txtCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFirstName)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactNumber)
                            .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNIC)
                        .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSideB.setBackground(new java.awt.Color(255, 255, 255));
        pnlSideB.setPreferredSize(new java.awt.Dimension(500, 100));

        lblAddress.setText("Address");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblLastName.setText("Last Name ");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other/Ok Filled-20.png"))); // NOI18N

        lblEmail.setText("Email ");

        javax.swing.GroupLayout pnlSideBLayout = new javax.swing.GroupLayout(pnlSideB);
        pnlSideB.setLayout(pnlSideBLayout);
        pnlSideBLayout.setHorizontalGroup(
            pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideBLayout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(pnlSideBLayout.createSequentialGroup()
                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(pnlSideBLayout.createSequentialGroup()
                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addGap(20, 20, 20))
        );
        pnlSideBLayout.setVerticalGroup(
            pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAddress)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLastName)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSideBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCustomerInformationLayout = new javax.swing.GroupLayout(pnlCustomerInformation);
        pnlCustomerInformation.setLayout(pnlCustomerInformationLayout);
        pnlCustomerInformationLayout.setHorizontalGroup(
            pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerInformationLayout.createSequentialGroup()
                .addComponent(pnlSideA, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSideB, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
        );
        pnlCustomerInformationLayout.setVerticalGroup(
            pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerInformationLayout.createSequentialGroup()
                .addGroup(pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlSideB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addGroup(pnlCustomerInformationLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlSideA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        pnlToolBox.setBackground(new java.awt.Color(221, 221, 221));

        btnGenerateNewGuestId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Generate_New_Guest_ID_def.png"))); // NOI18N
        btnGenerateNewGuestId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateNewGuestIdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerateNewGuestIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerateNewGuestIdMouseExited(evt);
            }
        });

        btnMakeBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Make_Booking_def.png"))); // NOI18N
        btnMakeBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMakeBookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMakeBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMakeBookingMouseExited(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Clear_def.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Report_def.png"))); // NOI18N
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlToolBoxLayout = new javax.swing.GroupLayout(pnlToolBox);
        pnlToolBox.setLayout(pnlToolBoxLayout);
        pnlToolBoxLayout.setHorizontalGroup(
            pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolBoxLayout.createSequentialGroup()
                .addComponent(btnGenerateNewGuestId)
                .addGap(0, 0, 0)
                .addComponent(btnMakeBooking)
                .addGap(0, 0, 0)
                .addComponent(btnClear)
                .addGap(0, 0, 0)
                .addComponent(btnReport)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlToolBoxLayout.setVerticalGroup(
            pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlToolBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnReport)
                .addComponent(btnClear))
            .addComponent(btnMakeBooking, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(btnGenerateNewGuestId, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tblmenu.setBackground(new java.awt.Color(52, 73, 94));
        tblmenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblmenu.setForeground(new java.awt.Color(255, 255, 255));
        tblmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Menu No", "Food Item", "Menu Type"
            }
        ));
        tblmenu.setGridColor(new java.awt.Color(189, 195, 199));
        tblmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmenuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblmenu);

        javax.swing.GroupLayout MLayout = new javax.swing.GroupLayout(M);
        M.setLayout(MLayout);
        MLayout.setHorizontalGroup(
            MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlToolBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCustomerInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
                    .addComponent(pnlBookingDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        MLayout.setVerticalGroup(
            MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MLayout.createSequentialGroup()
                .addComponent(pnlToolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnlCustomerInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBookingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(M, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 405, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateNewGuestIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateNewGuestIdMouseEntered
        // TODO add your handling code here:
         changebtnname.buttonState(btnGenerateNewGuestId, "Generate_New_Guest_ID_hov");
    }//GEN-LAST:event_btnGenerateNewGuestIdMouseEntered

    private void btnGenerateNewGuestIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateNewGuestIdMouseExited
        // TODO add your handling code here:
        changebtnname.buttonState(btnGenerateNewGuestId, "Generate_New_Guest_ID_def");
    }//GEN-LAST:event_btnGenerateNewGuestIdMouseExited

    private void btnMakeBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMakeBookingMouseEntered
        // TODO add your handling code here:
        changebtnname.buttonState(btnMakeBooking, "Make_Booking_hov");
    }//GEN-LAST:event_btnMakeBookingMouseEntered

    private void btnMakeBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMakeBookingMouseExited
        // TODO add your handling code here:
        changebtnname.buttonState(btnMakeBooking, "Make_Booking_def");
    }//GEN-LAST:event_btnMakeBookingMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        changebtnname.buttonState(btnClear, "Clear_hov");
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        changebtnname.buttonState(btnClear, "Clear_def");
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        // TODO add your handling code here:
        changebtnname.buttonState(btnReport, "Report_hov");
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        // TODO add your handling code here:
        changebtnname.buttonState(btnReport, "Report_def");
    }//GEN-LAST:event_btnReportMouseExited

    private void txtCustomerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNoActionPerformed

    private void txtAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdvanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdvanceActionPerformed

    private void btnMakeBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMakeBookingMouseClicked
       
        
//          if(itp.isEmpty(txtCustomerNo, "Customer No field is empty"))
//           {
//               if(itp.isEmpty(txtFirstName, "First Name field is empty"))
//               {
//                 if(itp.isEmpty(txtLastName, "Last Name field is empty"))
//                 { 
//                      if(itp.isEmpty(txtContactNo, "Contact No field is empty"))
//                     {
//                          if(itp.isEmpty(txtNIC, "NIC field is empty"))
//                          {
//                              if(itp.isEmpty(txtAddress, "Address field is empty"))
//                              {
//                                  if(itp.isEmpty(txtEmail, "Email field is empty"))
//                                  {
//                                   //   if(itp.isEmpty(txtBookingNo, "Booking No field is empty"))
//                                    // {
//////                                          if(obj.isEmpty(cmbFunctionType,"Function Type field is empty"))
//////                                          {
//                                              if(itp.isEmpty(txtTotalNoOfGuest, "Total No Of Guest field is empty"))
//                                              {
//                                                  if(itp.isEmpty(txtAdvance, "Advance field is empty"))
//                                                  {
//                                                      
//                                                          //if(itp.isEmpty(txtStartTime, "Start Time field is empty"))
//                                                         // {
//                                                             // if(itp.isEmpty(txtEndTime, "End Time field is empty"))
//                                                              //{
//                                                                  if(itp.isValidEmailAddress(txtEmail))
//                                                                  {
//                                                                      if(itp.isPositive(txtTotalNoOfGuest, "Enter Positive value for Total No Of Guest"))
//                                                                      {
//                                                                          
                                                                        obj.isSameDate();  
                                                                        
                                                                          
//                                                                     // }
//                                                                  }
//                                                              //}
//                                                          //}
//                                                      
//                                                  }
//                                              }
//                                         // }
//////                                      }
//                                  }
//                              }
//                          }
//                      }
//                  }
//               }
//           }
    }//GEN-LAST:event_btnMakeBookingMouseClicked

    private void txtTotalNoOfGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalNoOfGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalNoOfGuestActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        obj.clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnGenerateNewGuestIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateNewGuestIdMouseClicked
        // TODO add your handling code here:
        obj.generateCustomerNo();
    }//GEN-LAST:event_btnGenerateNewGuestIdMouseClicked

    private void txtBookingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookingNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookingNoActionPerformed

    private void tblmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmenuMouseClicked
        
    }//GEN-LAST:event_tblmenuMouseClicked

    private void cmbMenuNoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbMenuNoPropertyChange
        obj.selectMenu();
    }//GEN-LAST:event_cmbMenuNoPropertyChange

    private void cmbEndTimePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbEndTimePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEndTimePropertyChange

    private void cmbStartTimePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbStartTimePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStartTimePropertyChange

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:
        
        
            
        
    }//GEN-LAST:event_jDateChooser1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel M;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnGenerateNewGuestId;
    private javax.swing.JLabel btnMakeBooking;
    private javax.swing.JLabel btnReport;
    public static javax.swing.JComboBox<String> cmbEndTime;
    public static javax.swing.JComboBox<String> cmbFunctionType;
    public static javax.swing.JComboBox<String> cmbMenuNo;
    public static javax.swing.JComboBox<String> cmbStartTime;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAdvance;
    private javax.swing.JLabel lblBookingNo;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFunctionType;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMenuPackageNo;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblTotalNoofGuests;
    private javax.swing.JPanel pnlBookingDetails;
    private javax.swing.JPanel pnlCustomerInformation;
    private javax.swing.JPanel pnlSideA;
    private javax.swing.JPanel pnlSideB;
    private javax.swing.JPanel pnlSidea;
    private javax.swing.JPanel pnlSideb;
    private javax.swing.JPanel pnlToolBox;
    public static javax.swing.JTable tblmenu;
    public static javax.swing.JTextField txtAddress;
    public static javax.swing.JTextField txtAdvance;
    public static javax.swing.JTextField txtBookingNo;
    public static javax.swing.JTextField txtContactNo;
    public static javax.swing.JTextField txtCustomerNo;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtFirstName;
    public static javax.swing.JTextField txtLastName;
    public static javax.swing.JTextField txtNIC;
    public static javax.swing.JTextField txtTotalNoOfGuest;
    // End of variables declaration//GEN-END:variables
}
